

PAGE_WIDTH = 1100
PAGE_HEIGHT = 650
BLUE_COLOR = "#5E95FF"
WHITE_COLOR = "#FFFFFF"
RED_COLOR = "#D22B2B"
HOVER_RED_COLOR = "#EE4B2B"
GREEN_COLOR = "#4CBB17"
HOVER_GREEN_COLOR = "#0BDA51"
MAIN_TITLE_FONT = ("Arial", 18)
APP_TITLE = "XP - Excel to PDF"